// This file will be auto-generated by Supabase CLI
// Run: npm run db:generate to update types

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          name: string
          role: 'student' | 'instructor' | 'admin'
          avatar: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          name: string
          role?: 'student' | 'instructor' | 'admin'
          avatar?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          role?: 'student' | 'instructor' | 'admin'
          avatar?: string
          created_at?: string
          updated_at?: string
        }
      }
      courses: {
        Row: {
          id: string
          title: string
          subtitle: string | null
          description: string
          category: string
          level: string
          language: string
          price: number
          original_price: number | null
          duration: string
          image_url: string | null
          instructor_id: string | null
          is_published: boolean
          enrollment_count: number
          rating: number
          review_count: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          subtitle?: string | null
          description: string
          category: string
          level: string
          language?: string
          price: number
          original_price?: number | null
          duration: string
          image_url?: string | null
          instructor_id?: string | null
          is_published?: boolean
          enrollment_count?: number
          rating?: number
          review_count?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title?: string
          subtitle?: string | null
          description?: string
          category?: string
          level?: string
          language?: string
          price?: number
          original_price?: number | null
          duration?: string
          image_url?: string | null
          instructor_id?: string | null
          is_published?: boolean
          enrollment_count?: number
          rating?: number
          review_count?: number
          created_at?: string
          updated_at?: string
        }
      }
      lessons: {
        Row: {
          id: string
          course_id: string
          section_id: string | null
          title: string
          description: string | null
          order_index: number
          duration: string | null
          lesson_type: 'video' | 'text' | 'quiz' | 'assignment'
          vimeo_url: string | null
          vimeo_video_id: string | null
          content: string | null
          is_preview: boolean
          is_published: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          course_id: string
          section_id?: string | null
          title: string
          description?: string | null
          order_index: number
          duration?: string | null
          lesson_type?: 'video' | 'text' | 'quiz' | 'assignment'
          vimeo_url?: string | null
          vimeo_video_id?: string | null
          content?: string | null
          is_preview?: boolean
          is_published?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          course_id?: string
          section_id?: string | null
          title?: string
          description?: string | null
          order_index?: number
          duration?: string | null
          lesson_type?: 'video' | 'text' | 'quiz' | 'assignment'
          vimeo_url?: string | null
          vimeo_video_id?: string | null
          content?: string | null
          is_preview?: boolean
          is_published?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      enrollments: {
        Row: {
          id: string
          user_id: string
          course_id: string
          enrolled_at: string
          completed_at: string | null
          progress_percentage: number
        }
        Insert: {
          id?: string
          user_id: string
          course_id: string
          enrolled_at?: string
          completed_at?: string | null
          progress_percentage?: number
        }
        Update: {
          id?: string
          user_id?: string
          course_id?: string
          enrolled_at?: string
          completed_at?: string | null
          progress_percentage?: number
        }
      }
      orders: {
        Row: {
          id: string
          user_id: string
          course_id: string
          amount: number
          currency: string
          status: 'pending' | 'completed' | 'failed' | 'cancelled' | 'refunded'
          payment_intent_id: string | null
          payment_method: 'stripe' | 'paypal' | 'apple_pay'
          customer_name: string | null
          customer_email: string | null
          customer_address: any | null
          completed_at: string | null
          refunded_at: string | null
          refund_amount: number | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          course_id: string
          amount: number
          currency?: string
          status?: 'pending' | 'completed' | 'failed' | 'cancelled' | 'refunded'
          payment_intent_id?: string | null
          payment_method?: 'stripe' | 'paypal' | 'apple_pay'
          customer_name?: string | null
          customer_email?: string | null
          customer_address?: any | null
          completed_at?: string | null
          refunded_at?: string | null
          refund_amount?: number | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          course_id?: string
          amount?: number
          currency?: string
          status?: 'pending' | 'completed' | 'failed' | 'cancelled' | 'refunded'
          payment_intent_id?: string | null
          payment_method?: 'stripe' | 'paypal' | 'apple_pay'
          customer_name?: string | null
          customer_email?: string | null
          customer_address?: any | null
          completed_at?: string | null
          refunded_at?: string | null
          refund_amount?: number | null
          created_at?: string
          updated_at?: string
        }
      }
    }
  }
} 